### ISSUE TITLE
Cannot require com.wotbrew.idx namespace: Must hint overloaded method: toArray

### ISSUE THREAD

**Issue by orolle** [wotbrew/idx#1]
I looked into vector.clj source code and it seems good. No idea why this happens.

I use leinigen and included the dependency [com.wotbrew/idx "0.1.0"] then I :required [com.wotbrew.idx :as idx] in my namespace.
I use [org.clojure/clojure "1.10.1"] 
I use OpenJDK 11.0.8 on Ubuntu 18.04.

#error {
 :cause Must hint overloaded method: toArray
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling deftype* at (com/wotbrew/impl/vector.clj:7:1).
   :data #:clojure.error{:phase :compile-syntax-check, :line 7, :column 1, :source com/wotbrew/impl/vector.clj, :symbol deftype*}
   :at [clojure.lang.Compiler analyzeSeq Compiler.java 7115]}
  {:type java.lang.IllegalArgumentException
   :message Must hint overloaded method: toArray
   :at [clojure.lang.Compiler$NewInstanceMethod parse Compiler.java 8497]}]
 :trace
 [[clojure.lang.Compiler$NewInstanceMethod parse Compiler.java 8497]
  [clojure.lang.Compiler$NewInstanceExpr build Compiler.java 8059]
  [clojure.lang.Compiler$NewInstanceExpr$DeftypeParser parse Compiler.java 7935]
  [clojure.lang.Compiler analyzeSeq Compiler.java 7107]
  [clojure.lang.Compiler analyze Compiler.java 6789]
  [clojure.lang.Compiler analyze Compiler.java 6745]
  [clojure.lang.Compiler$BodyExpr$Parser parse Compiler.java 6118]
  [clojure.lang.Compiler$LetExpr$Parser parse Compiler.java 6436]
  [clojure.lang.Compiler analyzeSeq Compiler.java 7107]
  [clojure.lang.Compiler analyze Compiler.java 6789]
  [clojure.lang.Compiler analyze Compiler.java 6745]
  [clojure.lang.Compiler$BodyExpr$Parser parse Compiler.java 6120]
  [clojure.lang.Compiler$FnMethod parse Compiler.java 5467]
  [clojure.lang.Compiler$FnExpr parse Compiler.java 4029]
  [clojure.lang.Compiler analyzeSeq Compiler.java 7105]
  [clojure.lang.Compiler analyze Compiler.java 6789]
  [clojure.lang.Compiler eval Compiler.java 7174]
  [clojure.lang.Compiler load Compiler.java 7636]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6839 invoke core.clj 6126]
  [clojure.core$load invokeStatic core.clj 6125]
  [clojure.core$load doInvoke core.clj 6109]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5908]
  [clojure.core$load_one invoke core.clj 5903]
  [clojure.core$load_lib$fn__6780 invoke core.clj 5948]
  [clojure.core$load_lib invokeStatic core.clj 5947]
  [clojure.core$load_lib doInvoke core.clj 5928]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$load_libs invokeStatic core.clj 5985]
  [clojure.core$load_libs doInvoke core.clj 5969]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$require invokeStatic core.clj 6007]
  [clojure.core$require doInvoke core.clj 6007]
  [clojure.lang.RestFn invoke RestFn.java 457]
  [com.wotbrew.impl.ext$eval14107$loading__6721__auto____14108 invoke ext.clj 1]
  [com.wotbrew.impl.ext$eval14107 invokeStatic ext.clj 1]
  [com.wotbrew.impl.ext$eval14107 invoke ext.clj 1]
  [clojure.lang.Compiler eval Compiler.java 7177]
  [clojure.lang.Compiler eval Compiler.java 7166]
  [clojure.lang.Compiler load Compiler.java 7636]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6839 invoke core.clj 6126]
  [clojure.core$load invokeStatic core.clj 6125]
  [clojure.core$load doInvoke core.clj 6109]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5908]
  [clojure.core$load_one invoke core.clj 5903]
  [clojure.core$load_lib$fn__6780 invoke core.clj 5948]
  [clojure.core$load_lib invokeStatic core.clj 5947]
  [clojure.core$load_lib doInvoke core.clj 5928]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$load_libs invokeStatic core.clj 5985]
  [clojure.core$load_libs doInvoke core.clj 5969]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$require invokeStatic core.clj 6007]
  [clojure.core$require doInvoke core.clj 6007]
  [clojure.lang.RestFn invoke RestFn.java 436]
  [com.wotbrew.idx$eval14101$loading__6721__auto____14102 invoke idx.cljc 1]
  [com.wotbrew.idx$eval14101 invokeStatic idx.cljc 1]
  [com.wotbrew.idx$eval14101 invoke idx.cljc 1]
  [clojure.lang.Compiler eval Compiler.java 7177]
  [clojure.lang.Compiler eval Compiler.java 7166]
  [clojure.lang.Compiler load Compiler.java 7636]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6839 invoke core.clj 6126]
  [clojure.core$load invokeStatic core.clj 6125]
  [clojure.core$load doInvoke core.clj 6109]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5908]
  [clojure.core$load_one invoke core.clj 5903]
  [clojure.core$load_lib$fn__6780 invoke core.clj 5948]
  [clojure.core$load_lib invokeStatic core.clj 5947]
  [clojure.core$load_lib doInvoke core.clj 5928]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$load_libs invokeStatic core.clj 5985]
  [clojure.core$load_libs doInvoke core.clj 5969]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$require invokeStatic core.clj 6007]
  [clojure.core$require doInvoke core.clj 6007]
  [clojure.lang.RestFn invoke RestFn.java 930]
  [incremental_datalog.core$eval149$loading__6721__auto____150 invoke core.cljc 1]
  [incremental_datalog.core$eval149 invokeStatic core.cljc 1]
  [incremental_datalog.core$eval149 invoke core.cljc 1]
  [clojure.lang.Compiler eval Compiler.java 7177]
  [clojure.lang.Compiler eval Compiler.java 7166]
  [clojure.lang.Compiler load Compiler.java 7636]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6839 invoke core.clj 6126]
  [clojure.core$load invokeStatic core.clj 6125]
  [clojure.core$load doInvoke core.clj 6109]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5908]
  [clojure.core$load_one invoke core.clj 5903]
  [clojure.core$load_lib$fn__6780 invoke core.clj 5948]
  [clojure.core$load_lib invokeStatic core.clj 5947]
  [clojure.core$load_lib doInvoke core.clj 5928]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$load_libs invokeStatic core.clj 5985]
  [clojure.core$load_libs doInvoke core.clj 5969]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$require invokeStatic core.clj 6007]
  [clojure.core$require doInvoke core.clj 6007]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [user$eval5 invokeStatic form-init6129161856543787012.clj 1]
  [user$eval5 invoke form-init6129161856543787012.clj 1]
  [clojure.lang.Compiler eval Compiler.java 7177]
  [clojure.lang.Compiler eval Compiler.java 7166]
  [clojure.lang.Compiler eval Compiler.java 7166]
  [clojure.lang.Compiler load Compiler.java 7636]
  [clojure.lang.Compiler loadFile Compiler.java 7574]
  [clojure.main$load_script invokeStatic main.clj 475]
  [clojure.main$init_opt invokeStatic main.clj 477]
  [clojure.main$init_opt invoke main.clj 477]
  [clojure.main$initialize invokeStatic main.clj 508]
  [clojure.main$null_opt invokeStatic main.clj 542]
  [clojure.main$null_opt invoke main.clj 539]
  [clojure.main$main invokeStatic main.clj 664]
  [clojure.main$main doInvoke main.clj 616]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.main main main.java 40]]}

**Comment by orolle** [comment]
https://github.com/clj-commons/ordered/pull/37/files
Type hint for Java 11
(^objects toArray [this ^objects dest] ...)

**Comment by wotbrew** [comment]
Ah I see, with java 11 overload disambiguation is required for toArray. Should be an easy fix. I'll get to it as soon as I can.

**Comment by wotbrew** [comment]
Should be fixed in the just released 0.1.1 @orolle, thanks for the report
